# Generated by Django 5.0.1 on 2024-02-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studen',
            new_name='Student',
        ),
    ]
