# Generated by Django 5.0.1 on 2024-02-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_studen_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
