# Generated by Django 5.0.1 on 2024-02-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
